# Generated by Django 5.0.6 on 2024-06-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='estado',
            field=models.CharField(choices=[('Iniciado', 'Iniciado'), ('En_proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Archivado', 'Archivado')], default='Iniciado', max_length=20),
        ),
    ]
