# Generated by Django 5.0.6 on 2024-06-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0003_reclamo_mensaje_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='departamento',
            field=models.CharField(default='No especificado', max_length=100),
            preserve_default=False,
        ),
    ]
